### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Luchanso** [fastup-kit/blog#14]
## UI/UX
- [ ] Add multiply language switcher
- [ ] Restyle blog post header
- [ ] Add photo preview on top
- [ ] Cross Posting from other sources (Just Label)
- [ ] Adaptive layout (Mobile/Tablet)
- [ ] Add share buttons
- [ ] Twitter integration
- [ ] Commenting platform

## Technical
- [ ] Add intgration via CI/CD - publish new content in social
  - [ ] Telegram Channel
  - [ ] Twitter
  - [ ] RSS Mailchimp
- [ ] Add simple theme configuration
- [ ] Add https://github.com/garmeeh/next-seo
- [ ] Add simple "like" API with nextJS
- [ ] e2e testing
